/*
SQLyog Ultimate v11.11 (32 bit)
MySQL - 5.1.40-community 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `product` (
	`productid` int (10),
	`productname` varchar (90),
	`productprice` double ,
	`producttitle` varchar (150),
	`productintroduction` varchar (600),
	`productimage` varchar (300),
	`productcount` int (10),
	`productsail` int (10),
	`productweight` int (10),
	`productsize` varchar (150),
	`productoneid` varchar (60),
	`producttwoid` varchar (60),
	`productthreeid` varchar (300),
	`productstatus` int (4),
	`productstartdatetime` datetime ,
	`productenddatetime` datetime ,
	`businessid` int (10),
	`productaddress` varchar (150),
	`sendtypeid` int (3),
	`productpageview` int (10)
); 
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('5','恒源祥织毛衣','268','恒源祥羊毛开衫男薄款2018春季青年打底衫外套纯色毛衣针织开衫潮','aaa','images/sweater.jpg','358','627','1','','cloth','cloth_man','cloth_man_heknitting','2','2018-03-17 22:18:20',NULL,'1','浙江嘉兴','3','245');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('6','Lilbetter卫衣男连帽','168','Lilbetter卫衣男连帽 韩版运动外套潮嘻哈卫衣假两件男士套头卫衣','aa','images/jacket.jpg','569','4573','1','','cloth','cloth_man','cloth_man_protect','1','2018-03-17 22:21:37',NULL,'1','浙江杭州','4','365');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('7','珊瑚绒睡衣','148','珊瑚绒睡衣男士秋冬款加厚加绒冬季春天法兰绒春秋男装家居服套装','a','images/sleepcloths.jpg','1489','1071','0','','cloth','cloth_man','cloth_man_nighty','4','2018-03-17 22:28:59',NULL,'1','广东汕头','2','124');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('8','花花公子板鞋男运动休闲鞋','149','花花公子板鞋男运动休闲鞋男春季潮鞋透气鞋子男韩版潮流白色男鞋','a','images/sleepshoes.jpg','1269','3458','0','','cloth','cloth_shoes','cloth_shoes_manlie','4','2018-03-17 22:34:25',NULL,'1','福建泉州','8','3256');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('9','马丁靴男英伦冬季加绒棉靴','298','马丁靴男英伦冬季加绒棉靴男靴高帮皮靴军靴复古真皮靴子男沙漠靴','a','images/boot.jpg','453','132','0','','cloth','cloth_shoes','cloth_shoes_martin','4','2018-03-17 22:42:09',NULL,'1','广东广州','4','235');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('10','IDX/爱定客男鞋帆布鞋','299','IDX/爱定客男鞋帆布鞋经典情侣款高帮鞋百搭韩版平底学生潮板鞋','a','images/shoes.jpg','130','244','0','','cloth','cloth_shoes','cloth_shoes_canvas','4','2018-03-17 22:50:21',NULL,'1','福建厦门 ','4','154');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('11','裤子','260','新款帅T中性潮男裤子韩版修身显瘦小脚裤27码26西服裤子西裤','a','images/pants.jpg','100','5','0','','cloth','cloth_man','cloth_man_hepants','5','2018-03-17 22:55:07',NULL,'1','浙江杭州','7','254');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('12','istep涂鸦ins帆布鞋','119','istep涂鸦ins帆布鞋女高帮学生韩版百搭手绘ulzzang原宿超火板鞋 ','a','images/womanshoes.jpg','736','722','0',NULL,'cloth','cloth_shoes','cloth_shoes_canvas','4','2018-03-17 23:08:07',NULL,'1','山东青岛','3','897');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('13','高跟鞋  ','159','Daphne/达芙妮春优雅蕾丝细跟性感尖头浅口后系带高跟鞋单鞋女','a','images/heightshoes.jpg','56','306','0',NULL,'cloth','cloth_shoes','cloth_shoes_high','4','2018-03-17 23:10:35',NULL,'1','上海','3','564');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('14','思卡琪马丁靴','398','思卡琪马丁靴女真皮英伦帅气前系带短靴子2017秋冬新款大码女鞋','a','images/womanboots.jpg','64','177','1',NULL,'cloth','cloth_shoes','cloth_shoes_martin','4','2018-03-17 23:14:33',NULL,'1','浙江金华','4','100');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('15','阔腿微喇叭裤八分牛仔裤','78','阔腿微喇叭裤八分牛仔裤女九分裤高腰春装2018新款ins超火的裤子','a','images/womanpants.jpg','1657','3354','0',NULL,'cloth','cloth_women','cloth_women_pants','2','2018-03-17 23:17:14',NULL,'1','广东东菀','3','2154');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('16','CHARLES＆KEITH单鞋','299','CHARLES＆KEITH单鞋女CK1-70390149绒面尖头水钻雪花方扣平底女鞋 ','a','images/womanshortshoes.jpg','12','544','0',NULL,'cloth','cloth_shoes','cloth_shoes_flattie','4','2018-03-17 23:20:44',NULL,'1','上海','4','32');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('17','芬腾居家长袖睡衣','159','芬腾居家长袖睡衣女春秋冬季全棉质休闲卡通针织纯棉家居服套装','a','images/womansleepclothes.jpg','15','1644','0',NULL,'cloth','cloth_women','cloth_women_nighty','4','2018-03-17 23:26:13',NULL,'1','广东汕头','7','54');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('18','初语2018春装连帽宽松加绒卫衣','169','初语2018春装连帽宽松加绒卫衣女韩版薄款学生套头粉色上衣帽衫潮','a','images/womanclothes.jpg','56','6088','0',NULL,'cloth','cloth_women','cloth_women_coat','4','2018-03-17 23:29:46',NULL,'1','广东广州','1','120');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('19','迪赛尼斯2018早春新品纯色短款薄外套','319','迪赛尼斯2018早春新品纯色短款薄外套百搭显瘦毛衣针织开衫女装','a','images/womansweater.jpg','108','42','1',NULL,'cloth','cloth_women','cloth_women_knitting','2','2018-03-17 23:32:27',NULL,'1','浙江杭州','1','65');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('20','笔记本','6199','Lenovo/联想 拯救者 R720-15IKBN I5/8G/双硬盘/1050Ti 4G游戏本','a','images/minicomputer.jpg','32','1544','3',NULL,'numeral','numeral_computer','numeral_computer_notebook','4','2018-03-17 23:37:19',NULL,'1','四川成都 ','4','1245');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('21','得力不锈钢尺','5.9','得力不锈钢尺 直尺金属长尺15/20/30/50cm刻度尺铁尺子小学生文具','a','images/femalerule.jpg','4351','1759','0',NULL,'female','female_childpen','female_childpen_rule','4','2018-03-17 23:41:43',NULL,'1','广东深圳','2','2154');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('22','西门子电冰箱 ','8099','电冰箱 8099  SIEMENS/西门子 KA92NE9CTI 变频无霜 对开门双开门家用大电冰箱','a','images/numeralfridge.jpg','26','175','80',NULL,'numeral','numeral_wiring','numeral_wiring_fridge','5','2018-03-17 23:46:51',NULL,'1','西安','4','124');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('23','黑冰睡袋','658','黑冰睡袋B400/B700/B1000/B1500成人轻量羽绒睡袋户外露营-10度','a','images/sleep.jpg','1','147','1',NULL,'beauty','beauty_sheet','beauty_sheet_sack','5','2018-03-17 23:52:46',NULL,'1','浙江台州','2','21');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('24','凡丁堡台灯卧室床头灯','178','凡丁堡 台灯卧室床头灯 现代简约北欧美式台灯时尚个性创意客厅灯','a','images/light.jpg','493','358','0',NULL,'beauty','beauty_lamp','beauty_lamp_lamp','2','2018-03-18 00:23:35',NULL,'1','广东东菀','3','354');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('25','大卫拖把桶旋转四驱动免手洗','228','大卫拖把桶旋转四驱动免手洗拖布桶拖地自动甩干墩布拓扑家用托把 ','a','images/generalmop.jpg','90774','4205','0',NULL,'general','general_menage','general_menage_mop','2','2018-03-18 00:27:27',NULL,'1','浙江金华','3','5452');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('26','8公斤变频滚筒洗衣机','1799','8公斤变频滚筒洗衣机全自动家用智能静音Midea/美的 MG80V330WDX  ','a','images/wash.jpg','132','3442','8',NULL,'numeral','numeral_wiring','numeral_wiring_washer','4','2018-03-18 00:30:58',NULL,'1','西安','3','321');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('27','室内晾衣架落地单杆式挂衣架','19.6','室内晾衣架落地单杆式挂衣架折叠凉衣杆简易卧室挂衣服架子晒被架','a','images/generalclothesrack.jpg','4756','53215','2',NULL,'general','general_receive','general_receive_clothesrack','4','2018-03-18 00:33:50',NULL,'1','河南郑州','2','6548');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('28','手机','999','Huawei/华为 畅享7 32G 全网通官方正品4G手机 ','a','images/phone.jpg','2030','49164','0',NULL,'numeral','numeral_handset','','4','2018-03-18 00:38:56',NULL,'1','广东深圳','4','3215');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('29','幼儿配方奶粉','175','美素佳儿金装幼儿配方奶粉3段','a','images/milk.jpg','860','16594','1',NULL,'female','female_milkpowder','','2','2018-03-18 00:44:09',NULL,'1','西安','1','1245');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('30','Dell/戴尔一体机电脑','3580','Dell/戴尔一体机电脑5460游戏i3/i5办公家用触屏23.8高清台式全套','1','images/computer.jpg','9','72','3',NULL,'numeral','numeral_computer','','4','2018-03-18 01:07:31',NULL,'1','上海','1','100');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('31','林氏木业儿童床','3238','林氏木业儿童床双层女孩多功能公主单人床儿童房家具组合套装DI5A',NULL,'images/femalechildbed.jpg','275','79','1',NULL,'female','female_childbed',NULL,'4',NULL,NULL,'1','广东佛山','2','65');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('32','北包包斜挎菱格小包包','59','北包包斜挎菱格小包包女韩版2018新款简约百搭迷你链条女包单肩包',NULL,'images/inclinedbox2.jpg','5237','1931','1',NULL,'box','box_inclined',NULL,'2',NULL,NULL,'1','河北保定','4','2544');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('33','金狐狸小方包','238','金狐狸小方包2018新款女包时尚欧美星辰单肩包迷你链条斜挎小包潮',NULL,'images/inclinedbox.jpg','10565','1350','1',NULL,'box','box_inclined',NULL,'4',NULL,NULL,'1','广东广州','4','325');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('34','左西童装男童卫衣春装','75','左西童装男童卫衣春装2018新款儿童长袖连帽上衣中大童春秋韩版潮',NULL,'images/femalechild2.jpg','29','211','1',NULL,'female','female_child',NULL,'4',NULL,NULL,'1','无锡','4','215');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('35','安奈儿童装女童无袖连衣裙','299','安奈儿童装女童无袖连衣裙2018夏季新款迪士尼公主A字裙EG823283',NULL,'images/femalechild.jpg','130','215','1',NULL,'female','female_child',NULL,'4',NULL,NULL,'1','广东东菀','2','124');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('36','好邻居多伴果夹心巧克力','33.8','好邻居多伴果夹心巧克力星空棒棒糖网红女友零食喜糖果批发500g',NULL,'images/catechocolate.jpg','1565','6042','1',NULL,'cate','cate_chocolate',NULL,'4',NULL,NULL,'1','福建泉州','2','2446');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('37','训练双肩包','269','Nike/耐克官方 NIKEBRASILIA训练双肩包（中型）BA5329',NULL,'images/diesisbox.jpg','1596','1704','1',NULL,'box','box_diesis',NULL,'4',NULL,NULL,'1','上海','2','1552');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('38','牛津大学书包','168','牛津大学书包男小学生3-4-6五年级男孩男童女孩女童护脊儿童背包',NULL,'images/bookbox2.jpg','364','361','2',NULL,'box','box_satchel',NULL,'4',NULL,NULL,'1','上海','1','324');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('39','幼儿园书包','76','幼儿园书包男童迪士尼汽车麦昆小孩2-3-5学前班儿童宝宝双肩背包',NULL,'images/bookbox.jpg','178','2548','2',NULL,'box','box_satchel',NULL,'4',NULL,NULL,'1','上海','4','245');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('40','真皮女士手包','238','真皮女士手包女手拿包女大容量2018新款百搭气质手抓包女包斜挎软',NULL,'images/fistbox2.jpg','2349','197','1',NULL,'box','box_fist',NULL,'4',NULL,NULL,'1','广东广州','8','215');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('41','皮尔卡丹正品手包','399','皮尔卡丹正品手包男真皮拉链鳄鱼纹软牛皮男士钱包长款休闲手拿包',NULL,'images/fistbox.jpg','668','608','1',NULL,'box','box_fist',NULL,'4',NULL,NULL,'1','广东广州','2','845');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('42','2017新款卓梵阿玛尼男士钱包','268','2017新款卓梵 阿玛尼男士钱包长款真皮潮青年手拿包男拉链手包男',NULL,'images/bursebox2.jpg','542','50','1',NULL,'box','box_burse',NULL,'4',NULL,NULL,'1','湖南长沙','7','356');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('43','皮尔卡丹正品钱包','299','皮尔卡丹正品钱包男长款商务休闲青年男士皮夹软牛皮真皮钱夹潮',NULL,'images/bursebox.jpg','87','1130','1',NULL,'box','box_burse',NULL,'4',NULL,NULL,'1','广东广州','4','215');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('44','纳兰杜2018新款真牛皮小包包','149','纳兰杜2018新款真牛皮小包包韩版迷你手机包单肩斜挎小包时尚女包',NULL,'images/minibox2.jpg','1','435','1',NULL,'box','box_min',NULL,'5',NULL,NULL,'1','广东广州','2','654');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('45','金狐狸包包女豆腐包','199','金狐狸包包女豆腐包2018新款迷你链条包韩版小方包单肩斜挎包小包',NULL,'images/minibox.jpg','184','3537','1',NULL,'box','box_min',NULL,'4',NULL,NULL,'1','广东肇庆','2','545');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('46','拉杆箱行李箱铝框旅行箱','188','拉杆箱行李箱铝框旅行箱万向轮女男26学生密码箱包20寸24皮箱子28',NULL,'images/trunkbox2.jpg','1469','82026','1',NULL,'box','box_trunk',NULL,'4',NULL,NULL,'1','浙江温州','4','5642');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('47','变色龙爱华仕拉杆箱','499','变色龙爱华仕拉杆箱男20寸旅行箱',NULL,'images/trunkbox.jpg','202','1011','2',NULL,'box','box_trunk',NULL,'4',NULL,NULL,'1','广东惠州','2','331');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('48','电脑包','41','苹果戴尔华硕13/14/15/15.6/17.3寸男女防震单肩手提笔记本电脑包',NULL,'images/computerbox.jpg','367','14569','1',NULL,'box','box_computer',NULL,'4',NULL,NULL,'1','上海','2','236');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('49','120克纯手工中秋月饼','5.5','120克纯手工中秋月饼出量饼干零食特产月饼什锦广西百色哈密瓜',NULL,'images/catecakemoon.jpg','5000','3265','2',NULL,'cate','cate_cake_moon',NULL,'4',NULL,NULL,'1','那坡县新村食品加工厂','8','4100');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('50','辣媳妇100gx5袋咔咔炝辣鸡爪子','34.99','辣媳妇100gx5袋咔咔炝辣鸡爪子重庆麻辣凤爪零食批发辣味熟食小吃',NULL,'images/catemeat.jpg','4500','3265','1',NULL,'cate','cate_fallow_flesh',NULL,'4',NULL,NULL,'1','重庆','1','3456');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('51','Polo胸包男牛津布休闲男包单肩包','139','Polo胸包男牛津布休闲男包单肩包斜背包韩版潮男士包包单肩斜挎包',NULL,'images/box2.jpg','290','426','1',NULL,'box','box_trunk',NULL,'4',NULL,NULL,'1','广东广州','8','1645');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('52','拉杆箱行李箱铝框旅行箱','188','拉杆箱行李箱铝框旅行箱万向轮女男26学生密码箱包20寸24皮箱子28',NULL,'images/box.jpg','1469','82008','1',NULL,'box','box_trunk',NULL,'4',NULL,NULL,'1','浙江温州','4','1245');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('53','BUBM耳机包收纳包数据线','23','BUBM耳机包收纳包数据线充电器数码U盘蓝牙迷你便携盒袋子保护套',NULL,'images/numeral2.jpg','7129','2723','1',NULL,'numeral','numeral_handset','numeral_handset_fittings','4',NULL,NULL,'1','浙江杭洲','1','1244');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('54','iphonex无线充电器','118','iphonex无线充电器苹果x手机8plus三星s8通用QI专用原装iPhone X',NULL,'images/numeral.jpg','1009','2793','1',NULL,'numeral','numeral_handset','numeral_handset_fittings','4',NULL,NULL,'1','广东深圳','8','1265');
insert into `product` (`productid`, `productname`, `productprice`, `producttitle`, `productintroduction`, `productimage`, `productcount`, `productsail`, `productweight`, `productsize`, `productoneid`, `producttwoid`, `productthreeid`, `productstatus`, `productstartdatetime`, `productenddatetime`, `businessid`, `productaddress`, `sendtypeid`, `productpageview`) values('55','贝因美婴儿奶瓶','49','贝因美婴儿奶瓶新生儿玻璃宽口径宝宝储奶带手柄母婴用品',NULL,'images/female2.jpg','1688','7583','1',NULL,'female','female_child',NULL,'4',NULL,NULL,'1','浙江杭州','2','2136');
